config/routes.rb
Rails.application.routes.draw do

  get 'teacher/index'

  get 'teacher/modules'

  get 'workers/index'

  get 'modules/index'

  get 'groups/index'

  get 'system/index'

  root 'index#index'

  get 'index/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/admin' => 'dashboard#admin'

  get 'settings' => 'system#index'

  post '/change/lang' => 'users#change_locale'

  get 'management/workers' => 'workers#index'
  get 'management/worker/new' => 'workers#new'

  get 'management/students' => 'students#index'
  get 'management/student/new' => 'students#new'

  get 'management/modules' => 'modules#index'
  get 'management/module/new' => 'modules#new'
  post 'management/module/create' => 'modules#create'

  get 'management/groups' => 'groups#index'
  get 'management/group/new' => 'groups#new'
  post 'management/group/new' => 'groups#create'

  get 'storage/group/:id' => 'groups#show'
  get 'storage/module/:id' => 'modules#show'

  get 'api' => 'api#index'
  get 'api/departments' => 'api#departments'

  get 'api/professions' => 'api#professions'
  get 'api/professions/:department' => 'api#professions'

  get 'api/groups' => 'api#groups'
  get 'api/groups/:profession' => 'api#groups'

  get 'api/students' => 'api#students'

  get 'teacher/modules' => 'teacher#modules'

  get 'teacher/module/show/:id' => 'teacher#show_module'
  get 'teacher/module/edit/:id' => 'teacher#edit_module'
  post 'teacher/module/edit/:id' => 'teacher#update_module'

  resources :users
  resources :students
  resources :groups
  resources :dashboard, only: :index

  scope :management do
    resources :workers
    resources :professions
  end

end

app/models/chair.rb
class Chair < ActiveRecord::Base
  belongs_to :department
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :chairs
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :students
  belongs_to :profession

  def get_code
    self.get_course + self.alias
  end

  def get_course
    now = Time.new
    course = now.year - self.year
    if (course == 0)
      course = 1;
    elsif (now.month > 8)
      course = course + 1
    end
    course.to_s
  end

  def get_code_profession_name
    self.get_code + ' ' + self.profession.name
  end
end

app/models/mixed_group.rb
class MixedGroup < ActiveRecord::Base
  has_and_belongs_to_many :students
  belongs_to :department
end

app/models/module_sheet.rb
class ModuleSheet < ActiveRecord::Base
  has_one :module_deadline
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  belongs_to :department
  has_many :groups
end

app/models/right.rb
class Right < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  def set_user(user)
    if !RolesUser.find_by(user_id: user, role_id: self.id) && User.find_by(id: user) != nil
      RolesUser.create(user_id: user, role_id: self.id)
    end
  end
end

app/models/roles_user.rb
class RolesUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_and_belongs_to_many :mixed_groups

  def get_full_name
    self.first_name + ' ' + self.last_name + ' ' + self.middle_name
  end

  def get_group_code
    self.group.get_code
  end

  def get_course
    now = Time.new
    course = now.year - self.group.year
    if (course == 0)
      course = 1;
    elsif (now.month > 8)
      course = course + 1
    end
    course.to_s
  end

  def get_module_sheet(deadline)
    ModuleSheet.find_by(module_deadline_id: deadline, student_id: self.id)
  end

end

app/models/study_year.rb
class StudyYear < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  has_one :student
  has_one :worker
  has_secure_password

  def set_role(role)
    if !RolesUser.find_by(user_id: self.id, role_id: role) && Role.find_by(id: role) != nil
      RolesUser.create(user_id: self.id, role_id: role)
    end
  end

  def is(role_name)
    if Role.find_by(name: role_name) != nil
      role = Role.find_by(name: role_name)
    else
      return false
    end
    return RolesUser.find_by(user_id: self.id, role_id: role.id) ? true : false
  end

  def get_roles
    array = []
    User.find(self.id).roles.each { |k| array << 'DashboardController::' + k.name }
    array
  end

  def get_full_name
    #todo:fix reference self.worker, self.student
    if Worker.where(id: self.worker_id).length != 0
      human = Worker.find(self.worker_id)
    else
      human = Student.find(self.student_id)
    end
    human.get_full_name
  end
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :user
  def get_full_name
    self.first_name + ' ' + self.last_name + ' ' + self.middle_name
  end
end

app/controllers/workers_controller.rb
class WorkersController < DashboardController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  helper_method :b_worker_management_name
  add_breadcrumb :b_worker_management_name, :management_students_path
  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    add_breadcrumb __(@worker.get_full_name), :management_students_path
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  protected
    def b_worker_management_name
      __('Worker Management')
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:first_name, :last_name, :middle_name, :sex, :birth_date, :position_id, :is_disabled)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/role_helper.rb
module RoleHelper
  def role_css_class(role_name)
    case role_name
      when 'root'
         'label-danger'
      when 'admin'
         'label-info'
      when 'student'
         'label-success'
      else
         'label-default'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= bootstrap_form_for @worker, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10', url: {action: 'new'}, html: {class: 'form-horizontal'} do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, 'error') %> prohibited this worker from being saved:</h2>
      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.text_field :middle_name %>
    <%= f.select :sex, sex_list.map { |g| [g[:title], g[:value]] }, required: true %>
    <%= f.date_select :birth_date %>
    <%= f.number_field :position_id %>
    <%= f.check_box :is_disabled %>
    <%= f.submit %>
<% end %>

app/views/workers/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to __('Add a Worker'), '/management/worker/new', class: 'btn btn-default'%>
  </div>
</div>

<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Middle name</th>
      <th>Sex</th>
      <th>Birth date</th>
      <th>Position</th>
      <th>Is disabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.first_name %></td>
        <td><%= worker.last_name %></td>
        <td><%= worker.middle_name %></td>
        <td><%= worker.sex %></td>
        <td><%= worker.birth_date %></td>
        <td><%= worker.position_id %></td>
        <td><%= worker.is_disabled %></td>
        <td><%= link_to __('Show'), worker, class: 'btn btn-default' %></td>
        <td><%= link_to __('Edit'), edit_worker_path(worker), class: 'btn btn-default' %></td>
        <td><%= link_to __('Destroy'), worker, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @worker.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @worker.last_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @worker.middle_name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @worker.sex %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @worker.birth_date %>
</p>

<p>
  <strong>Position:</strong>
  <%= @worker.position_id %>
</p>

<p>
  <strong>Is disabled:</strong>
  <%= @worker.is_disabled %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker), class: 'btn btn-default' %> |
<%= link_to 'Back', workers_path, class: 'btn btn-default' %>