config/routes.rb
Rails.application.routes.draw do

  get 'teacher/index'

  get 'teacher/modules'

  get 'workers/index'

  get 'modules/index'

  get 'groups/index'

  get 'system/index'

  root 'index#index'

  get 'index/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/admin' => 'dashboard#admin'

  get 'settings' => 'system#index'

  post '/change/lang' => 'users#change_locale'

  get 'management/workers' => 'workers#index'
  get 'management/worker/new' => 'workers#new'

  get 'management/students' => 'students#index'
  get 'management/student/new' => 'students#new'

  get 'management/modules' => 'modules#index'
  get 'management/module/new' => 'modules#new'
  post 'management/module/create' => 'modules#create'

  get 'management/groups' => 'groups#index'
  get 'management/group/new' => 'groups#new'
  post 'management/group/new' => 'groups#create'

  get 'storage/group/:id' => 'groups#show'
  get 'storage/module/:id' => 'modules#show'

  get 'api' => 'api#index'
  get 'api/departments' => 'api#departments'

  get 'api/professions' => 'api#professions'
  get 'api/professions/:department' => 'api#professions'

  get 'api/groups' => 'api#groups'
  get 'api/groups/:profession' => 'api#groups'

  get 'api/students' => 'api#students'

  get 'teacher/modules' => 'teacher#modules'

  get 'teacher/module/show/:id' => 'teacher#show_module'
  get 'teacher/module/edit/:id' => 'teacher#edit_module'
  post 'teacher/module/edit/:id' => 'teacher#update_module'

  resources :users
  resources :students
  resources :groups
  resources :dashboard, only: :index

  scope :management do
    resources :workers
    resources :professions
  end

end

app/models/chair.rb
class Chair < ActiveRecord::Base
  belongs_to :department
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :chairs
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :students
  belongs_to :profession

  def get_code
    self.get_course + self.alias
  end

  def get_course
    now = Time.new
    course = now.year - self.year
    if (course == 0)
      course = 1;
    elsif (now.month > 8)
      course = course + 1
    end
    course.to_s
  end

  def get_code_profession_name
    self.get_code + ' ' + self.profession.name
  end
end

app/models/mixed_group.rb
class MixedGroup < ActiveRecord::Base
  has_and_belongs_to_many :students
  belongs_to :department
end

app/models/module_sheet.rb
class ModuleSheet < ActiveRecord::Base
  has_one :module_deadline
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  belongs_to :department
  has_many :groups
end

app/models/right.rb
class Right < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  def set_user(user)
    if !RolesUser.find_by(user_id: user, role_id: self.id) && User.find_by(id: user) != nil
      RolesUser.create(user_id: user, role_id: self.id)
    end
  end
end

app/models/roles_user.rb
class RolesUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_and_belongs_to_many :mixed_groups

  def get_full_name
    self.first_name + ' ' + self.last_name + ' ' + self.middle_name
  end

  def get_group_code
    self.group.get_code
  end

  def get_course
    now = Time.new
    course = now.year - self.group.year
    if (course == 0)
      course = 1;
    elsif (now.month > 8)
      course = course + 1
    end
    course.to_s
  end

  def get_module_sheet(deadline)
    ModuleSheet.find_by(module_deadline_id: deadline, student_id: self.id)
  end

end

app/models/study_year.rb
class StudyYear < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  has_one :student
  has_one :worker
  has_secure_password

  def set_role(role)
    if !RolesUser.find_by(user_id: self.id, role_id: role) && Role.find_by(id: role) != nil
      RolesUser.create(user_id: self.id, role_id: role)
    end
  end

  def is(role_name)
    if Role.find_by(name: role_name) != nil
      role = Role.find_by(name: role_name)
    else
      return false
    end
    return RolesUser.find_by(user_id: self.id, role_id: role.id) ? true : false
  end

  def get_roles
    array = []
    User.find(self.id).roles.each { |k| array << 'DashboardController::' + k.name }
    array
  end

  def get_full_name
    #todo:fix reference self.worker, self.student
    if Worker.where(id: self.worker_id).length != 0
      human = Worker.find(self.worker_id)
    else
      human = Student.find(self.student_id)
    end
    human.get_full_name
  end
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :user
  def get_full_name
    self.first_name + ' ' + self.last_name + ' ' + self.middle_name
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/role_helper.rb
module RoleHelper
  def role_css_class(role_name)
    case role_name
      when 'root'
         'label-danger'
      when 'admin'
         'label-info'
      when 'student'
         'label-success'
      else
         'label-default'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<% page_title __('Home') %>
<h1>Пошук історії успішності студента</h1>
<br>
<div class="col-lg-5 ">
  <div class="panel panel-primary">
    <div class="panel-heading"><h3 class="panel-title">Підказка</h3></div>
    <div class="panel-body">Введіть номер залікової книжки або ПІП студента</div>
  </div>
</div>
<div class="clearfix"></div>
<br>
<div class="input-group input-group-lg col-lg-7">
  <span class="input-group-addon">@</span>
  <input type="text" class="form-control" placeholder="Введіть данні для пошуку...">
  <span class="input-group-btn">
        <button class="btn btn-default" type="button">Пошук</button>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:page_title) ? content_for(:page_title) : __('Deanery') %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render template: 'layouts/top_menu' %>
<div class="container">
  <div class="well">
    <div class="container-fluid">
      <%= render_breadcrumbs :tag => :li, :separator => '', :builder => ::BootstrapBreadcrumbsBuilder %>
      <%= yield %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  //helper variables
  window.DATE = {
    year: <%= Time.now.year %>,
    month: <%= Time.now.month %>,
    day: <%= Time.now.day %>,
    hour: <%= Time.now.hour %>,
    min: <%= Time.now.min %>,
    sec: <%= Time.now.sec %>,
    zone: '<%= Time.now.zone %>'
  }
  window.SERVER = {
    time: new Date(DATE.year, DATE.month, DATE.day, DATE.hour, DATE.min, DATE.sec, 00)
  }
  window.BASE_URL = '<%= base_url %>';
  window.LANG = '<%= current_lang %>';
</script>
</body>
</html>

app/views/layouts/top_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Меню</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to __('Deanery'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><a href="#" class="glyphicon glyphicon-user"></a></li>
        <!--<li class="active"><a href="#"><%= current_user.login %></a></li>-->
        <li class="active"><a href="#"><%= current_user.get_full_name %></a></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= __('User') %> <span class="caret"></span></a>
          <% if current_user %>
          <ul class="dropdown-menu logged-in">
            <li><%= link_to __('Dashboard'), dashboard_path %></li>
            <li><a href="#">Профіль</a></li>
            <li><a href="#">Налаштування</a></li>
            <li class="locales">
              <% I18n.available_locales.each do |l| %>
                  <% active = l.to_s == current_lang ? 'active' : '' %>
                  <%= content_tag :b, l, class: active, onclick: 'changeLang("'+l.to_s+'")' %>
              <% end %>
            </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to __('Log out'), logout_path, method: "delete" %></li>
          </ul>
          <% else %>
            <ul class="dropdown-menu not-logged-in">
              <li><%= render template: 'sessions/new' %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>